name:                icake206
version:             0.1.0.0
github:              "edwardgeorge/icake206"
license:             BSD3
author:              "Edward George"
maintainer:          "edwardgeorge@gmail.com"
copyright:           "2018 Edward George"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/edwardgeorge/icake206#readme>

dependencies:
- base >= 4.7 && < 5
- microlens

default-extensions:
- RecordWildCards

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  icake206-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icake206
